spring:
  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: huangxing
      password: Spring
      database: test
      authenticationDatabase: admin
server:
  port: 8088