// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.hx.calculator;

public interface BinaryOperationReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hx.calculator.BinaryOperationReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 result = 1;</code>
   */
  int getResult();
}
