// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.hx.calculator;

public interface BinaryOperationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hx.calculator.BinaryOperationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 number1 = 1;</code>
   */
  int getNumber1();

  /**
   * <code>sint32 number2 = 2;</code>
   */
  int getNumber2();
}
