// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.hx.calculator;

/**
 * <pre>
 * The request message containing the user's name.
 * </pre>
 *
 * Protobuf type {@code com.hx.calculator.BinaryOperationRequest}
 */
public  final class BinaryOperationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hx.calculator.BinaryOperationRequest)
    BinaryOperationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BinaryOperationRequest.newBuilder() to construct.
  private BinaryOperationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BinaryOperationRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BinaryOperationRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BinaryOperationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            number1_ = input.readSInt32();
            break;
          }
          case 16: {

            number2_ = input.readSInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hx.calculator.CalculatorProto.internal_static_com_hx_calculator_BinaryOperationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hx.calculator.CalculatorProto.internal_static_com_hx_calculator_BinaryOperationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hx.calculator.BinaryOperationRequest.class, com.hx.calculator.BinaryOperationRequest.Builder.class);
  }

  public static final int NUMBER1_FIELD_NUMBER = 1;
  private int number1_;
  /**
   * <code>sint32 number1 = 1;</code>
   */
  public int getNumber1() {
    return number1_;
  }

  public static final int NUMBER2_FIELD_NUMBER = 2;
  private int number2_;
  /**
   * <code>sint32 number2 = 2;</code>
   */
  public int getNumber2() {
    return number2_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (number1_ != 0) {
      output.writeSInt32(1, number1_);
    }
    if (number2_ != 0) {
      output.writeSInt32(2, number2_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (number1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, number1_);
    }
    if (number2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(2, number2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hx.calculator.BinaryOperationRequest)) {
      return super.equals(obj);
    }
    com.hx.calculator.BinaryOperationRequest other = (com.hx.calculator.BinaryOperationRequest) obj;

    if (getNumber1()
        != other.getNumber1()) return false;
    if (getNumber2()
        != other.getNumber2()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NUMBER1_FIELD_NUMBER;
    hash = (53 * hash) + getNumber1();
    hash = (37 * hash) + NUMBER2_FIELD_NUMBER;
    hash = (53 * hash) + getNumber2();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hx.calculator.BinaryOperationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hx.calculator.BinaryOperationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hx.calculator.BinaryOperationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hx.calculator.BinaryOperationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hx.calculator.BinaryOperationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code com.hx.calculator.BinaryOperationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hx.calculator.BinaryOperationRequest)
      com.hx.calculator.BinaryOperationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hx.calculator.CalculatorProto.internal_static_com_hx_calculator_BinaryOperationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hx.calculator.CalculatorProto.internal_static_com_hx_calculator_BinaryOperationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hx.calculator.BinaryOperationRequest.class, com.hx.calculator.BinaryOperationRequest.Builder.class);
    }

    // Construct using com.hx.calculator.BinaryOperationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      number1_ = 0;

      number2_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hx.calculator.CalculatorProto.internal_static_com_hx_calculator_BinaryOperationRequest_descriptor;
    }

    @java.lang.Override
    public com.hx.calculator.BinaryOperationRequest getDefaultInstanceForType() {
      return com.hx.calculator.BinaryOperationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.hx.calculator.BinaryOperationRequest build() {
      com.hx.calculator.BinaryOperationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hx.calculator.BinaryOperationRequest buildPartial() {
      com.hx.calculator.BinaryOperationRequest result = new com.hx.calculator.BinaryOperationRequest(this);
      result.number1_ = number1_;
      result.number2_ = number2_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hx.calculator.BinaryOperationRequest) {
        return mergeFrom((com.hx.calculator.BinaryOperationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hx.calculator.BinaryOperationRequest other) {
      if (other == com.hx.calculator.BinaryOperationRequest.getDefaultInstance()) return this;
      if (other.getNumber1() != 0) {
        setNumber1(other.getNumber1());
      }
      if (other.getNumber2() != 0) {
        setNumber2(other.getNumber2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hx.calculator.BinaryOperationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hx.calculator.BinaryOperationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int number1_ ;
    /**
     * <code>sint32 number1 = 1;</code>
     */
    public int getNumber1() {
      return number1_;
    }
    /**
     * <code>sint32 number1 = 1;</code>
     */
    public Builder setNumber1(int value) {
      
      number1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 number1 = 1;</code>
     */
    public Builder clearNumber1() {
      
      number1_ = 0;
      onChanged();
      return this;
    }

    private int number2_ ;
    /**
     * <code>sint32 number2 = 2;</code>
     */
    public int getNumber2() {
      return number2_;
    }
    /**
     * <code>sint32 number2 = 2;</code>
     */
    public Builder setNumber2(int value) {
      
      number2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 number2 = 2;</code>
     */
    public Builder clearNumber2() {
      
      number2_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hx.calculator.BinaryOperationRequest)
  }

  // @@protoc_insertion_point(class_scope:com.hx.calculator.BinaryOperationRequest)
  private static final com.hx.calculator.BinaryOperationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hx.calculator.BinaryOperationRequest();
  }

  public static com.hx.calculator.BinaryOperationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BinaryOperationRequest>
      PARSER = new com.google.protobuf.AbstractParser<BinaryOperationRequest>() {
    @java.lang.Override
    public BinaryOperationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BinaryOperationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BinaryOperationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BinaryOperationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hx.calculator.BinaryOperationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

