// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.hx.calculator;

public final class CalculatorProto {
  private CalculatorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hx_calculator_BinaryOperationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hx_calculator_BinaryOperationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hx_calculator_BinaryOperationReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hx_calculator_BinaryOperationReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\022\021com.hx.calculator\":\n" +
      "\026BinaryOperationRequest\022\017\n\007number1\030\001 \001(\021" +
      "\022\017\n\007number2\030\002 \001(\021\"&\n\024BinaryOperationRepl" +
      "y\022\016\n\006result\030\001 \001(\0212\230\003\n\020SimpleCalculator\022[" +
      "\n\003add\022).com.hx.calculator.BinaryOperatio" +
      "nRequest\032\'.com.hx.calculator.BinaryOpera" +
      "tionReply\"\000\022_\n\005minus\022).com.hx.calculator" +
      ".BinaryOperationRequest\032\'.com.hx.calcula" +
      "tor.BinaryOperationReply\"\0000\001\022b\n\010multiply" +
      "\022).com.hx.calculator.BinaryOperationRequ" +
      "est\032\'.com.hx.calculator.BinaryOperationR" +
      "eply\"\000(\001\022b\n\006divide\022).com.hx.calculator.B" +
      "inaryOperationRequest\032\'.com.hx.calculato" +
      "r.BinaryOperationReply\"\000(\0010\001B.\n\021com.hx.c" +
      "alculatorB\017CalculatorProtoH\001P\001\242\002\003HLWb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hx_calculator_BinaryOperationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hx_calculator_BinaryOperationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hx_calculator_BinaryOperationRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", });
    internal_static_com_hx_calculator_BinaryOperationReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hx_calculator_BinaryOperationReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hx_calculator_BinaryOperationReply_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
